-author("Alex").
-record(field, {width, height, cells}).
-record(cell, {x, y, item}).
-define(IS_INSIDE(X, Y, Field), ((X > 0) and (Y > 0) and (X =< Field#field.width) and (Y =< Field#field.height))).